jcabi-matchers is a runtime dependency
Not sure if I'm missing something, but it seems to me `jcabi-matchers` is a runtime dependency and not just a test one.

It is used by `DefaultHtmlValidator`:
```
java.lang.NoClassDefFoundError: com/jcabi/matchers/XhtmlMatchers
	at com.jcabi.http.response.XmlResponse.assertXPath(XmlResponse.java:142)
	at com.jcabi.w3c.DefaultHtmlValidator.validate(DefaultHtmlValidator.java:87)
```